ZebRaid.RaidID = "75_4.22.2009"
ZebRaid.Signups = {
    "Althae:signed:tank:",
    "Beh:signed:tank:can do 1x25 and 1x10 I think, or i\'ll happily sitout, am too sleepy :x",
    "Cyric:signed:tank:",
    "Deviloflight:signed:tank:",
    "Iceberg:signed:tank:",
    "Bladesinger:signed:melee:",
    "Bur:signed:melee:",
    "Choobetta:signed:melee:",
    "Ilma:signed:melee:",
    "Karadk:signed:melee:",
    "Kaverin:signed:melee:",
    "Mute:signed:melee:",
    "Rakas:signed:melee:",
    "Udaganka:signed:melee:",
    "Zlyfer:signed:melee:",
    "Atranox:signed:healer:",
    "Chagas:signed:healer:",
    "Cholla:signed:healer:",
    "Erwinwardoom:signed:healer:",
    "Jiny:signed:healer:",
    "Pestius:signed:healer:",
    "Suzuka:signed:healer:",
    "Tiya:signed:healer:",
    "Vishy:signed:healer:",
    "Warstarter:signed:healer:",
    "Agnar:signed:ranged:",
    "Anabozo:signed:ranged:",
    "Auryn:signed:ranged:",
    "Dys:signed:ranged:",
    "Gwenth:signed:ranged:",
    "Kakalock:signed:ranged:",
    "Kanath:signed:ranged:",
    "Kolpa:signed:ranged:",
    "Mantie:signed:ranged:",
    "Pandina:signed:ranged:",
    "Vizeon:signed:ranged:",
    "Haades:unsure:ranged:will be late like 1 hour consider me as backup pls",
    "Enûnna:unsigned:healer:Going to a birthday, GL raiding =)",
    "Frostylady:unsigned:ranged:still home :(",
    "Killbunch:unsigned:healer:Darts",
};
