ZebRaid.RaidID = "82_5.4.2009"
ZebRaid.Signups = {
    "Althae:signed:tank:",
    "Cyric:signed:tank:",
    "Iceberg:signed:tank:",
    "Zerae:signed:tank:",
    "Bladesinger:signed:melee:",
    "Bur:signed:melee:",
    "Choobetta:signed:melee:",
    "Ilma:signed:melee:",
    "Karadk:signed:melee:Great !\nsame boss with :\n2 different tank\n3 different melee\n2 different healer\n2 different ranged Dps ...",
    "Kaverin:signed:melee:",
    "Rakas:signed:melee:",
    "Zlyfer:signed:melee:",
    "Aneor:signed:healer:",
    "Atranox:signed:healer:",
    "Chagas:signed:healer:",
    "Cholla:signed:healer:",
    "Enûnna:signed:healer:",
    "Jiny:signed:healer:",
    "Warstarter:signed:healer:",
    "Anabozo:signed:ranged:",
    "Auryn:signed:ranged:",
    "Dys:signed:ranged:",
    "Fasulye:signed:ranged:",
    "Frostylady:signed:ranged:",
    "Haades:signed:ranged:",
    "Kakalock:signed:ranged:",
    "Kanath:signed:ranged:",
    "Pandina:signed:ranged:",
    "Vizeon:signed:ranged:",
    "Beh:unsure:tank:I probably will be devastated at the end of the day, I worked overnight. If I can stay awake I\'ll come.",
    "Petree:unsure:melee:",
    "Erwinwardoom:unsigned:healer:Have a late meeting, so cant come",
};
