ZebRaid.RaidID = "id_id=21_1.11.2009"
ZebRaid.Signups = {
    "Beh:signed:tank:",
    "Iceberg:signed:tank:",
    "Petree:signed:tank:don\'t know if i should, got exam tomorrow morning at 8. ill know for sure at raid time",
    "Zerae:signed:tank:Might be a bit late",
    "Bur:signed:melee:",
    "Choobetta:signed:melee:",
    "Kaverin:signed:melee:",
    "Mute:signed:melee:",
    "Sóth:signed:melee:",
    "Zlyfer:signed:melee:",
    "Chagas:signed:healer:",
    "Erwinwardoom:signed:healer:",
    "Jiny:signed:healer:",
    "Vishy:signed:healer:",
    "Agnar:signed:ranged:",
    "Anabozo:signed:ranged:",
    "Dys:signed:ranged:",
    "Fasulye:signed:ranged:",
    "Frostylady:signed:ranged:",
    "Haades:signed:ranged:",
    "Kakalock:signed:ranged:",
    "Mantie:signed:ranged:",
    "Nephar:signed:ranged:",
    "Shanol:signed:ranged:",
    "Auryn:signed:hybrid w. heal:",
    "Cyric:signed:hybrid w. heal:",
    "Diya:signed:hybrid w. heal:",
    "Ilma:signed:hybrid w. heal:",
    "Karadine:signed:hybrid w. heal:",
    "Vizeon:signed:hybrid w. heal:",
    "Atranox:unsigned:healer:",
    "Cholla:unsigned:healer:Late christmas party with the company :)",
};
